### ISSUE TITLE
Fix parsing

### ISSUE THREAD

**Issue by vrtulka23** [vrtulka23/scinumtools#32]
>>> dip = DIP()
>>> dip.from_file('settings.dip')
>>> dip.parse()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/scinumtools/dip/dip.py", line 130, in parse
    node = self._determine_node(line)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/scinumtools/dip/dip.py", line 242, in _determine_node
    raise Exception(f"Incorrect format: {code}")
                                         ^^^^
NameError: name 'code' is not defined. Did you mean: 'node'?
>>>

**Comment by vrtulka23** [comment]
fixed in the newest commit
