### ISSUE TITLE
Substraction of scalars from dimensionless quantities 

### ISSUE THREAD

**Issue by vrtulka23** [vrtulka23/scinumtools#6]
>>> import scinumtools as snt
>>> a = snt.quant(34)
>>> a -= 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scinumtools/phys/units/QuantityClass.py", line 107, in __sub__
    return self._sub(self, other)
  File "scinumtools/phys/units/QuantityClass.py", line 101, in _sub
    magnitude = left.magnitude - right.to(left.baseunits).magnitude
  File "scinumtools/phys/units/QuantityClass.py", line 298, in to
    unit2 = Quantity(1,units)
  File "scinumtools/phys/units/QuantityClass.py", line 53, in __init__
    self.magnitude *= unit.magnitude
AttributeError: 'NoneType' object has no attribute 'magnitude'

**Comment by vrtulka23** [comment]
fixed in the newest version
